name: Feature request
description: Suggest a new option or a new behaviour
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What can you not do today?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should pgsrip do instead? Add the command line that you expect.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What do you do today to work around the problem?
